all: liga-led monitor sbutton sequencial sequencial2

liga-led: liga-led.c
	gcc liga-led.c -o liga-led -O2

monitor: monitor.c
	gcc monitor.c -o monitor -O2

sbutton: sbutton.c
	gcc sbutton.c -o sbutton -O2

sequencial: sequencial.c
	gcc sequencial.c -o sequencial -O2

sequencial2: sequencial2.c
	gcc sequencial2.c -o sequencial2 -O2

clean: 
	rm liga-led monitor sbutton sequencial sequencial2
